// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAOWaG7tdIY6a5kaB6yJ2e34ZW_A6sLQU',
    appId: '1:811016690663:web:85c9e2b064a079c31f7b42',
    messagingSenderId: '811016690663',
    projectId: 'night-owl-f4cce',
    authDomain: 'night-owl-f4cce.firebaseapp.com',
    storageBucket: 'night-owl-f4cce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGLdpDzt0uU-2KhZWOIkuQT2e-jiZ9C_4',
    appId: '1:811016690663:android:59fa6437167042f71f7b42',
    messagingSenderId: '811016690663',
    projectId: 'night-owl-f4cce',
    storageBucket: 'night-owl-f4cce.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAOWaG7tdIY6a5kaB6yJ2e34ZW_A6sLQU',
    appId: '1:811016690663:web:e8fa3b2eb29e6e7b1f7b42',
    messagingSenderId: '811016690663',
    projectId: 'night-owl-f4cce',
    authDomain: 'night-owl-f4cce.firebaseapp.com',
    storageBucket: 'night-owl-f4cce.firebasestorage.app',
  );
}
